const actions = {
	cart: {
		ADD_TO_CART: 'ADD_TO_CART',
		REMOVE_FROM_CART: 'REMOVE_FROM_CART',
		INCREASE_QUANTITY: 'INCREASE_QUANTITY',
		DECREASE_QUANTITY: 'DECREASE_QUANTITY',
	},
};

export default actions;
